name: Deploy website to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy website to `gh-pages`
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
          publish_branch: gh-pages
          allow_empty_commit: true
